# Generated by Django 4.2.6 on 2024-02-14 06:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            managers=[
                ('category_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
