# Generated by Django 4.2.6 on 2024-02-14 06:01

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('calc_clicks', models.IntegerField(default='0')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('on_sale', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100)], default=0)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('category_id', models.ManyToManyField(related_name='categories', to='new_shop.category')),
            ],
            managers=[
                ('product_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
