# Generated by Django 4.2.6 on 2024-02-14 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0003_categoryproduct_addcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='product_id',
        ),
        migrations.AddField(
            model_name='addcart',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='new_shop.product'),
        ),
    ]
